language: python
rvm:
    - "3.5"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"
    - "pypy"
    - "pypy3"
    - "pypy-5.3.1"
install: 
    - pip install -r requirements.txt
    - pip install .
script: 
    - py.test
